### ISSUE TITLE
Deleting of first item problem

### ISSUE THREAD

**Issue by Anton-Am** [unclead/yii2-multiple-input#34]
I've got a problem with deleting of first element. U can just to move up add button to column header for solving this problem.
![widget menu frontend index menu](https://cloud.githubusercontent.com/assets/2063230/9841562/eccee082-5aa9-11e5-9c95-d82c70c7a116.png)

**Comment by unclead** [comment]
Currently the main idea is that has to be at least one row in list. Your case can be solved the next way:
- add new property e.g. `enableEmptyList`
- if this property is true widget will render `add` button in the header of table

New property is necessary for BC. I will try to implement this feature soon or you can prepare PR.

**Comment by unclead** [comment]
Implemented via dd0d61d5e0dfb12537a3a186c5d1f5fb3f5f1c13
You can update to last revision
Let me know if this is what you wanted

**Comment by lorinczelod** [comment]
ok, but the + signed wanised... at least in MultipleInput example... with new allowEmptyList property

**Comment by unclead** [comment]
Ohhh yes, i forgot about this case

**Comment by unclead** [comment]
fixed via f96092cd62a7b292f6d80de76cca9716d92173df

**Comment by lorinczelod** [comment]
Great solution, but the 'title' question isn't solved.
The '+' sign staying there alone, without title, I can't find the proper solution unless  the one below.
Probably we need a new property to turn on/off the title and for BC.
(I think we need a title when 'allowEmptyList' is true...)
```
    protected function guessColumns()
    {
        if (empty($this->columns) && $this->hasModel()) {
            $this->columns = [
                [
                    'name' => $this->attribute,
                    'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
                    'title' =>$this->model->getAttributeLabel($this->attribute), // recommended line
                ]
            ];
        }
    }
    ```

**Comment by unclead** [comment]
Give me example of code which does not work.

Here is example without `title`

```
<?php
    echo $form->field($model, 'emails')->widget(MultipleInput::className(), [
        'limit' => 5,
        'allowEmptyList' => true
    ])
    ->label(false);
?>
```

![Example](http://prntscr.com/8gliiw)

**Comment by unclead** [comment]
It seems that I understood that you propose :smile: 

But this is another issue. Look at #35

**Comment by lorinczelod** [comment]
thank you :)

2015-09-15 19:31 GMT+03:00 Eugene Tupikov <notifications@github.com>:
